# Generated by Django 4.1.7 on 2023-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_home_party',
            field=models.BooleanField(default=False),
        ),
    ]
