# Generated by Django 4.1.7 on 2023-03-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_game_list_id_remove_items_list_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='fetch_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
