# Generated by Django 4.1.7 on 2023-03-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_items_fetch_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='bought',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
